export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const DONATION_SUCCESS = 'DONATION_SUCCESS';
export const DONATION_FAIL = "DONATION_FAIL";

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETSILS_FAIL = 'USER_DETSILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const LIST_FETCH_SUCCESS = 'LIST_FETCH_SUCCESS'
export const LIST_FETCH_FAIL = 'LIST_FETCH_FAIL'

export const Email_SEND = 'USER_EMAIL_SEND'
export const Email_FAIL = 'USER_EMAIL_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const AMOUNT_TRANSFER_REQUEST = 'AMOUNT_TRANSFER_REQUEST';
export const AMOUNT_TRANSFER_SUCCESS = 'AMOUNT_TRANSFER_SUCCESS';
export const AMOUNT_TRANSFER_FAIL = 'AMOUNT_TRANSFER_FAIL';
export const AMOUNT_TRANSFER_RESET = 'AMOUNT_TRANSFER_RESET';


export const ADMIN_REGISTER_REQUEST = 'ADMIN_TRANSFER_REQUEST';
export const ADMIN_REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAIL = 'REGISTER_FAIL';
export const AMOUNT_REGISTER_RESET = 'ADMIN_TRANSFER_RESET';

export const ADMIN_UPDATE_REQUEST = 'ADMIN_UPDATE_REQUEST';
export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS';
export const ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL';
export const ADMIN_UPDATE_RESET = 'ADMIN_UPDATE_RESET';

export const MANAGER_REGISTER_REQUEST = 'MANAGER_REGISTER_REQUEST';
export const MANAGER_REGISTER_SUCCESS = 'MANAGER_REGISTER_SUCCESS';
export const MANAGER_REGISTER_FAIL = 'MANAGER_REGISTER_FAIL';
export const MANAGER_REGISTER_RESET = 'MANAGER_REGISTER_RESET';

export const MANAGER_UPDATE_REQUEST = 'MANAGER_UPDATE_REQUEST';
export const MANAGER_UPDATE_SUCCESS = 'MANAGER_UPDATE_SUCCESS';
export const MANAGER_UPDATE_FAIL = 'MANAGER_UPDATE_FAIL';
export const MANAGER_UPDATE_RESET = 'MANAGER_UPDATE_RESET';

export const MANAGER_DELETE_REQUEST = 'MANAGER_DELETE_REQUEST';
export const MANAGER_DELETE_SUCCESS = 'MANAGER_DELETE_SUCCESS';
export const MANAGER_DELETE_FAIL = 'MANAGER_DELETE_FAIL';
export const MANAGER_DELETE_RESET = 'MANAGER_DELETE_RESET';

export const WORKER_REGISTER_REQUEST = 'WORKER_REGISTER_REQUEST';
export const WORKER_REGISTER_SUCCESS = 'WORKER_REGISTER_SUCCESS';
export const WORKER_REGISTER_FAIL = 'WORKER_REGISTER_FAIL';
export const WORKER_REGISTER_RESET = 'WORKER_REGISTER_RESET';

export const WORKER_UPDATE_REQUEST = 'MANAGER_UPDATE_REQUEST';
export const WORKER_UPDATE_SUCCESS = 'MANAGER_UPDATE_SUCCESS';
export const WORKER_UPDATE_FAIL = 'MANAGER_UPDATE_FAIL';
export const WORKER_UPDATE_RESET = 'MANAGER_UPDATE_REQUEST';

export const WORKER_DELETE_REQUEST = 'WORKER_DELETE_REQUEST';
export const WORKER_DELETE_SUCCESS = 'WORKER_DELETE_SUCCESS';
export const WORKER_DELETE_FAIL = 'WORKER_DELETE_FAIL';
export const WORKER_DELETE_RESET = 'WORKER_DELETE_RESET';